### ISSUE TITLE
Search formula modifications

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [synchrony/smsn#41]
(Apology: If I didn't have so many other pressing obligations I would just implement this instead of writing it down here.)

"And" would be cool for searches. I had an idea about human development, wanted to see if I already had an "early error" category or something similar, searched for "earl* err*", and got a ton of results none of the first many of which had both terms.

**Comment by joshsh** [comment]
Excuses, excuses.  Yes, an "and" would be nice.  Ever since the move to Neo4j 2.3, I fear entering more than one search term.  If Google can serve results for "this is a really long search" in 300ms, a local Neo4j+Lucene ought to be able to finish the job in a reasonable number of seconds.  Something isn't right.

**Comment by JeffreyBenjaminBrown** [comment]
We already have the and operator! A capitalized "AND" is all it takes.

**Comment by joshsh** [comment]
Forgot about that.  AND is vanilla Lucene syntax.  I'm almost tempted to replace every space in a search string with " AND " for the sake of speed.  One other quirk is that search is very literal about punctuation.  E.g. you can't search on "Einstein" and get "Einstein's brain".  You can't even search for text in quotes without actually including and escaping the quotes in the search string.

**Comment by JeffreyBenjaminBrown** [comment]
If space was "AND" could we still use "OR"?
